name: Build Marlin Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # Обновили до стабильной 3.11

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio

    - name: Run PlatformIO Build
      run: |
        # Инструкция: Если сборка снова упадет, замените "stm32f103rc_btt" в строке ниже 
        # на "STM32F103RE_btt" (строго с соблюдением регистра букв)
        pio run -e stm32f103rc_btt

    - name: Upload Firmware Artifact
      if: success() # Файл загрузится только при успешной сборке
      uses: actions/upload-artifact@v4
      with:
        name: Marlin-SKR-Mini-E3-V2
        path: .pio/build/**/firmware.bin
